### ISSUE TITLE
Steamworks API Macro

### ISSUE THREAD

**Issue by coreydwillis** [ChapelR/harlowe-macro-api#11]
Do you think it would be possible to create a Steamworks API Macro using this?

**Comment by ChapelR** [comment]
I'm not particularly familiar with the steamworks API, but in general the answer should be yes. Please note though that this project is not something I'm working on anymore, as Harlowe has since introduced custom macros and basic variable support for script tags.

**Comment by coreydwillis** [comment]
Thanks for taking the time to answer! I'll look into that further.
