### ISSUE TITLE
Macro submission: macro passages

### ISSUE THREAD

**Issue by rachekzone** [ChapelR/harlowe-macro-api#6]
> A gist with the source and documentation can be found [here](https://gist.github.com/rachek64/97ab6f71893072a153fe21c31ddbfe0b).

(If the documentation needs to be reworked to fit the rest of the site I can assist, but this is a pretty complicated macro to document.)

I found myself with a bunch of little complex calculations I needed to run regularly throughout my game, and I was able to halfway fake macros by making code-only passages that would read and write global variables to accept arguments and return results, and I could then `(display:)` the passage to run it.

That ended up being a hot mess, because the arguments and results would stick around forever as global variables, and the syntax was clumsy and verbose. Also, I had to use some complicated self-replacing hooks to make sure to not accidentally mess up the spacing and formatting on the calling passage.

---

I used this framework to hack into Harlowe ever so slightly to create real macro passages. This adds a `(macro:)` macro that accepts a suitable passage name (one that's been tagged with `macro`) and any arguments. The macro passage will immediately run off-screen, with the arguments array available in `_args` and the ability to return a value in `_result`. Everything is nicely isolated, and shouldn't interfere with the calling passage's formatting or variables.

For some additional sugar, tagging a passage with both `macro` and `auto-macro` will turn the entire passage into a first-class macro on startup, so you can just use `(macro-name: <...arguments>)` instead of `(macro: "macro name", <...arguments>)`.

More detailed info and caveats are available in the gist itself.

**Comment by ChapelR** [comment]
That's really neat, thanks. I'll probably convert/transpile it to ES5 for maximum browser support, but I'd definitely love to add it to the collection.
